[workspace]
resolver = "2"
members = ["crates/drifti-core", "crates/drifti-observer"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.84"
authors = ["Luca Becci <beccibrian@gmail.com>"]
repository = "https://github.com/lucabecci/drifti"

[workspace.lints.rust]
unsafe_code = "forbid"
